import { expect, test } from "bun:test";
import { SqlDatabase, type SqlDialect } from "@bolt/database";
import { count, defineEntity, OptimisticLockError, OrmSession, Repository } from "../src/index.ts";

const engines: readonly { dialect: SqlDialect; env: string }[] = [
  { dialect: "postgresql", env: "BOLT_POSTGRESQL_TEST_URL" },
  { dialect: "mysql", env: "BOLT_MYSQL_TEST_URL" },
  { dialect: "mariadb", env: "BOLT_MARIADB_TEST_URL" },
];
for (const { dialect, env } of engines) {
  const url = process.env[env];
  test.skipIf(!url)(`${dialect}: actual ORM CRUD, generated identities, query aggregation, optimistic locking, no-op updates and rollback`, async () => {
    const db = SqlDatabase.create({ dialect, url: url!, maxConnections: 3, allowPublicKeyRetrieval: process.env["BOLT_MYSQL_TEST_ALLOW_PUBLIC_KEY_RETRIEVAL"] === "1" });
    const table = `orm_${crypto.randomUUID().replaceAll("-", "").slice(0, 12)}`;
    interface Person { id: number; name: string; team: string; version: number; }
    const people = defineEntity<Person>({ table, columns: { id: { primaryKey: true, generated: true }, name: {}, team: {}, version: { version: true } } });
    const unversioned = defineEntity<Omit<Person, "version">>({ table, columns: { id: { primaryKey: true }, name: {}, team: {} } });
    await db.start();
    try {
      const identity = dialect === "postgresql" ? "INTEGER GENERATED BY DEFAULT AS IDENTITY" : "INTEGER AUTO_INCREMENT";
      await db.execute(`CREATE TABLE ${table} (id ${identity} PRIMARY KEY, name VARCHAR(100) NOT NULL, team VARCHAR(100) NOT NULL, version INTEGER NOT NULL)`);
      const repo = new Repository(db, people);
      const one = await repo.insert({ name: "One", team: "a" });
      const two = await repo.insert({ name: "Two", team: "a" });
      expect(one.id).toBe(1);
      expect(one.version).toBe(1);
      expect((await repo.query().where(p => p.name.startsWith("O")).single())?.id).toBe(1);
      expect(await repo.query().orderBy(p => p.id).skip(1).take(1).select(p => ({ name: p.name })).toList()).toEqual([{ name: "Two" }]);
      expect(await repo.query().groupBy(p => p.team).select(p => ({ team: p.team, total: count() })).toList()).toEqual([{ team: "a", total: 2 }]);
      const stale = { ...one };
      one.name = "Updated";
      await repo.update(one);
      expect(one.version).toBe(2);
      stale.name = "Stale";
      await expect(repo.update(stale)).rejects.toBeInstanceOf(OptimisticLockError);
      const plainRepo = new Repository(db, unversioned);
      await plainRepo.update({ id: two.id, name: two.name, team: two.team });
      const session = new OrmSession(db);
      const trackedOne = await session.find(people, { id: one.id });
      const trackedTwo = await session.find(people, { id: two.id });
      two.name = "Concurrent";
      await repo.update(two);
      trackedOne!.name = "Rollback";
      trackedTwo!.name = "Conflict";
      await expect(session.flush()).rejects.toBeInstanceOf(OptimisticLockError);
      expect((await repo.find({ id: one.id }))?.name).toBe("Updated");
      expect(trackedOne!.version).toBe(2);
      session.dispose();
      const inserted: Partial<Person> = { name: "Uncommitted", team: "b" };
      await expect(OrmSession.transaction(db, async scoped => {
        scoped.add(people, inserted);
        await scoped.flush();
        expect(inserted.id).toBeDefined();
        throw new Error("rollback outer transaction");
      })).rejects.toThrow("rollback outer");
      expect(inserted.id).toBeUndefined();
      expect(await repo.query().count()).toBe(2);
      await repo.delete(one);
      expect(await repo.find({ id: one.id })).toBeNull();
    } finally {
      await db.execute(`DROP TABLE IF EXISTS ${table}`);
      await db.close();
    }
  });
}
